//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Problem2.DistanceCalculatorClient.ServiceReferanceCalculator {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferanceCalculator.DistanceCalculator")]
    public interface DistanceCalculator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DistanceCalculator/CalcDistance", ReplyAction="http://tempuri.org/DistanceCalculator/CalcDistanceResponse")]
        double CalcDistance(WS_Homework01_Overview.Point startPoint, WS_Homework01_Overview.Point endPoint);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DistanceCalculator/CalcDistance", ReplyAction="http://tempuri.org/DistanceCalculator/CalcDistanceResponse")]
        System.Threading.Tasks.Task<double> CalcDistanceAsync(WS_Homework01_Overview.Point startPoint, WS_Homework01_Overview.Point endPoint);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DistanceCalculatorChannel : Problem2.DistanceCalculatorClient.ServiceReferanceCalculator.DistanceCalculator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DistanceCalculatorClient : System.ServiceModel.ClientBase<Problem2.DistanceCalculatorClient.ServiceReferanceCalculator.DistanceCalculator>, Problem2.DistanceCalculatorClient.ServiceReferanceCalculator.DistanceCalculator {
        
        public DistanceCalculatorClient() {
        }
        
        public DistanceCalculatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DistanceCalculatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DistanceCalculatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DistanceCalculatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double CalcDistance(WS_Homework01_Overview.Point startPoint, WS_Homework01_Overview.Point endPoint) {
            return base.Channel.CalcDistance(startPoint, endPoint);
        }
        
        public System.Threading.Tasks.Task<double> CalcDistanceAsync(WS_Homework01_Overview.Point startPoint, WS_Homework01_Overview.Point endPoint) {
            return base.Channel.CalcDistanceAsync(startPoint, endPoint);
        }
    }
}
